<?php

namespace SM\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitImagesRepository extends EntityRepository
{
    public function FindMeilleursVentes()
    {
      // Méthode 1 : en passant par l'EntityManager
      $queryBuilder = $this->_em->createQueryBuilder()
        ->select('i')
        ->from($this->_entityName, 'i')
        ->join('i.produit', 'p')
        ->addSelect('p')
        ->where('i.resolution = :resol')
        ->setParameter('resol', '231x383')
        ->orderBy('p.nbVente','DESC')
        ->setMaxResults(4)
      ;
      // Dans un repository, $this->_entityName est le namespace de l'entité gérée
      // Ici, il vaut donc OC\PlatformBundle\Entity\Advert

      // On récupère la Query à partir du QueryBuilder
      $query = $queryBuilder->getQuery();

      // On récupère les résultats à partir de la Query
      $results = $query->getResult();

      // On retourne ces résultats
      return $results;
    }
}
