parameters:
#    sm_femmes.example.class: SM\FemmesBundle\Example

services:
#    sm_femmes.example:
#        class: %sm_femmes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
